version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./plugins/:/var/lib/neo4j/plugins/